"""应用的 Prometheus 指标配置.

本模块负责设置和配置用于监控应用的 Prometheus 指标.
"""

from prometheus_client import Counter, Histogram, Gauge
from starlette_prometheus import metrics, PrometheusMiddleware

# 请求指标
http_requests_total = Counter("http_requests_total", "Total number of HTTP requests", ["method", "endpoint", "status"])

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds", "HTTP request duration in seconds", ["method", "endpoint"]
)

# 数据库指标
db_connections = Gauge("db_connections", "Number of active database connections")

# 自定义业务指标
orders_processed = Counter("orders_processed_total", "Total number of orders processed")

llm_inference_duration_seconds = Histogram(
    "llm_inference_duration_seconds",
    "Time spent processing LLM inference",
    ["model"],
    buckets=[0.1, 0.3, 0.5, 1.0, 2.0, 5.0],
)


llm_stream_duration_seconds = Histogram(
    "llm_stream_duration_seconds",
    "Time spent processing LLM stream inference",
    ["model"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
)

session_names_generated_total = Counter(
    "session_names_generated_total",
    "Total session names generated by the LLM",
    ["status"],  # "success" 或 "error"
)


def setup_metrics(app):
    """配置 Prometheus 指标中间件和接口.

    参数：
        app: FastAPI 应用实例.
    """
    # 添加 Prometheus 中间件
    app.add_middleware(PrometheusMiddleware)

    # 添加指标接口
    app.add_route("/metrics", metrics)
